WEB2/board/urls.py
from django.urls import path
from . import views


app_name = 'board'

urlpatterns = [
    path('', views.board_list, name="board_list"),
    path('write/', views.board_write, name="write"),
    path('detail/<int:id>/', views.board_detail, name="detail"),
    path('<int:del_id>/', views.board_delete, name="delete"),
    path('update/<int:up_id>/', views.board_update, name="update"),
    path('<int:post_id>', views.file_download, name="download"),
]

WEB2/config/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/', include('homeapp.urls')),
    path('/', include('homeapp.urls')),
    path('app/analysis/', include('analysisapp.urls', namespace='analysis')),
    path('app/account/', include('accountapp.urls', namespace='account')),
    path('app/board/', include('board.urls', namespace='board')),
]

urlpatterns += \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

WEB2/board/models.py
from django.db import models
from django.db.models.fields import CharField,\
    IntegerField, TextField, DateTimeField

label_name = 'board'


class QABoard(models.Model):
    id = IntegerField(primary_key=True, auto_created=True)
    user_id = CharField(max_length=150)
    title = TextField()
    content = TextField()
    answer_title = TextField()
    answer_content = TextField()
    create_time = DateTimeField(auto_now_add=True)
    update_time = DateTimeField(auto_now=True)
    file_name = models.ImageField(upload_to="Board/images",
                                  blank=True,
                                  null=True)

    def __str__(self):
        return self.title

    class Meta:
        db_table = 'QABoard'
        app_label = label_name
        managed = False

WEB2/board/views.py
# -*- coding: utf-8 -*-
import mimetypes
from django.shortcuts import render, redirect
from django.contrib import messages
from board.models import QABoard
from django.http import FileResponse


def board_list(request):
    postlist = QABoard.objects.all()
    return render(request, 'board/board_list.html', {'postlist': postlist})
# Create your views here.


def board_write(request):
    if request.method == "POST":
        # 관리자가 답글을 다는 경우
        if request.session['user_class'] == 99:
            post_id = request.POST.get('question_id')
            new_answer = QABoard.objects.get(id=post_id)

            answer_title = request.POST.get('answer_title')
            answer_content = request.POST.get('answer_content')

            new_answer.answer_title = answer_title
            new_answer.answer_content = answer_content
            new_answer.save()
            return redirect('/app/board/')

        # 사용자가 질문글을 작성하는 경우
        else:
            m_QABoard = QABoard()
            m_QABoard.user_id = request.session["user_id"]
            m_QABoard.title = request.POST.get("title")
            m_QABoard.content = request.POST.get('content')
            m_QABoard.file_name = request.FILES.get('file_name')
            m_QABoard.save()

            return redirect('/app/board/')

    return render(request, "board/board_write.html")


def board_detail(request, id):
    post = QABoard.objects.get(id=id)
    return render(request, 'board/board_detail.html', {'post': post})


def board_update(request, up_id):
    post_update = QABoard.objects.get(id=up_id)
    if request.method == "POST":
        post_update.title = request.POST.get('title')
        post_update.content = request.POST.get('content')
        if request.FILES.get('update_file_name'):
            post_update.file_name = request.FILES.get('update_file_name')
        else:
            post_update.file_name = post_update.file_name
        print(post_update.title)
        print(post_update.content)
        print(post_update.file_name)
        post_update.save()
        return redirect('/app/board/')
    else:
        return render(request, 'board/board_update.html', {
            'post_update': post_update
            }
        )


def board_delete(request, del_id):
    post_del = QABoard.objects.get(id=del_id)
    print(post_del)
    post_del.delete()
    messages.info(request, "삭제가 완료되었습니다. ")
    return redirect('/app/board/')


def file_download(request, post_id):
    file = QABoard.objects.get(id=post_id)
    file_path = file.file_name.path
    file_mimetype = mimetypes.guess_type(file_path)
    response = FileResponse(open(file_path, 'rb'), content_type=file_mimetype)
    response['X-Sendfile'] = file_path
    response['Content-Disposition'] = \
        'attachment;filename*=UTF-8\'\'%s' % file.file_name
    return response

WEB2/board/templates/board/board_detail.html
{% extends "base.html" %}
{% load static %} 

{% block content %}
{% block styles %}
    <link rel="stylesheet" href="{% static 'assets/css/board_css.css' %}?after" type="text/css"/> 
{% endblock %}
<div style='height:4rem;'>
    <br>
</div>
<div id="main">
    <div class="board">
        <h2>
            문의게시판
            <span> | 영업일 기준 1일 이내 답변됩니다!</span>
        
            {% comment %} 자기 글이거나 관리자일 때 수정, 삭제 가능  {% endcomment %}
            {% ifequal request.session.user_id post.user_id %}
                <a href="{% url 'board:delete' del_id=post.id %}">
                    삭제 >
                </a>
                <a href="{% url 'board:update' up_id=post.id %}">
                    수정 >
                </a>
            {% endifequal %}
            {% ifequal request.session.user_class 99 %}
                <a href="{% url 'board:delete' del_id=post.id %}">
                    삭제 >
                </a>
                <a href="{% url 'board:update' up_id=post.id %}">
                    수정 >
                </a>
            {% endifequal %}
            {% if post.file_name %}
                <a href="{% url 'board:download' post_id=post.id %}">
                    사진 다운로드 >
                </a>
            {% endif %}
        </h2>
        <section class="qna_list">
            {% if post.file_name %}
            <div style="overflow: hidden;display: flex;
align-items: center;justify-content: center;">
                <img src="{{ post.file_name.url }}" style="display: block;margin: 0 auto;max-width:100%"/>
            </div>
                {% endif %}
            <table class="table" style="table-layout:auto">
                    <tr class="text-center">
                        <th scope="col" width=20% style="font-weight:bold;font-size: 1.1vw;">제목</th>
                        <td width=80% class="board_td">{{ post.title }}</td>
                    </tr>
                    <tr class="text-center">
                        <th scope="col" class="board_td">내용</th>
                        <td class="board_td">{{ post.content }}</td>
                    </tr>
                    <hr>
                    {% if post.answer_title %}
                    <tr class="text-center">
                        <th scope="col" class="board_td">답변제목</th>
                        <td class="board_td">{{ post.answer_title }}</td>
                    </tr>
                    <tr class="text-center">
                        <th scope="col" class="board_td">답변내용</th>
                        <td class="board_td">{{ post.answer_content }}</td>
                    </tr>
                    {% endif %}
            </table>
        </section>


        {% comment %} 관리자일 경우(user_class=99) 답변이 아직 없을 시 답변 form을, 답변이 완료된 건에는 내용물을 보여줌 {% endcomment %}
        {% ifequal request.session.user_class 99 %}
            {% if not post.answer_title %}
            <hr>
                <h2>관리자기능 : 답글달기</h2>
                <form method="POST" action="{% url 'board:write' %}">
                    {% csrf_token %}
                    {% comment %} display:none으로 질문 글의 id를 받아와서 objects를 찾을 수 있게 함 {% endcomment %}
                    <input type="text" name="question_id" value={{ post.id }} style="display:none">
                    <div>
                        <label for="answer_title">제목</label><br>
                        <input type="text" name="answer_title" id="answer_title">
                    </div>
                    <div>
                        <label for="answer_content">내용</label><br>
                        <textarea name="answer_content" id="answer_content" cols="30" rows="10"></textarea>
                    </div>
                    <input type="submit" value="답글달기" />
                </form>
            {% endif %}
        {% endifequal %}
    </div>
</div>
{% endblock content %}

WEB2/board/templates/board/board_list.html
{% extends "base.html" %}
{% load static %} 

{% block content %}
{% block styles %}
    <link rel="stylesheet" href="{% static 'assets/css/board_css.css' %}?after" type="text/css"/> 
{% endblock %}
<div style='height:4rem'>
    <br>
</div>
<div id="main">
    <div class="board">
            <h2>
                문의게시판 
                <span> | 영업일 기준 1일 이내 답변됩니다!
                    {% if request.session.user_id %}
                        {% ifnotequal request.session.user_class 99 %}
                            <a href="{% url 'board:write' %}" id="write-button">
                                문의글쓰기 >
                            </a>
                        {% endifnotequal %}
                    {% endif %}
                    {% comment %} {% ifequal request.session.user_class 1 %}
                            <a href="{% url 'board:write' %}" id="write-button">
                                문의글쓰기 >
                            </a>
                    {% endifequal %} {% endcomment %}
                </span>
            </h2>
        <br/>
        <section class="qna_list">
            <table class="table" style="table-layout:auto;cellspacing:0;cellpadding:0">
                <thead class="thead-light" style="display:none">
                    <tr class="text-center">
                        <th scope="col">#</th>
                        <th scope="col">답변유무</th>
                        <th scope="col">제목</th>
                        <th scope="col">작성자</th>
                    </tr>
                </thead>
                <div class="container">
                    <tbody>
                        {% for list in postlist reversed %}
                        <tr class="text-center">
                            <th scope="row" width=5% class="board_td">
                                <span>{{ list.id }}</span>
                            </th>
                            <td width=10% height="0" class="board_td">
                                {% if list.answer_title %}
                                <div style="height:100%">
                                    <img src="{% static 'assets/images/게시판_답변완료.png' %}" height="100%" />
                                </div>
                                {% else %}
                                <div style="height:100%">
                                    <img  src="{% static 'assets/images/게시판_미답변.png' %}" height="100%" />
                                </div>
                                {% endif %}
                            </td>
                            <td width=75% class="board_td">
                                <a href="{% url 'board:detail' id=list.id %}">
                                <span>{{ list.title }}</span>
                                </a>
                            </td>
                            <td width=10% class="board_td">
                                <span>{{ list.user_id }}</span>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
            </table>
            </div>
        </section>
    </div>
</div>

{% endblock content %}

WEB2/board/templates/board/board_update.html
{% extends "base.html" %}
{% load static %} 

{% block content %}
{% block styles %}
    <link rel="stylesheet" href="{% static 'assets/css/board_css.css' %}?after" type="text/css"/> 
{% endblock %}
<div style='height:4rem;'>
    <br>
</div>
<div id="main">
    <div class="board">
        <form method="POST" action="{% url 'board:update' up_id=post_update.id %}" class="post-write" enctype="multipart/form-data">
            {% csrf_token %}
            {% if post_update.file_name %}
            <div style="overflow: hidden;display: flex;
            align-items: center;justify-content: center;">
                <img src="{{ post_update.file_name.url }}" style="display:block;margin: 0 auto;max-width:100%" /><br>
            </div>
            {% endif %}
            <br>
                <div>
                <label for="title">제목</label><br>
                <input type="text" name="title" id="title" value="{{ post_update.title }}" />
            </div>
            <div>
                <label for="content">내용</label><br>
                <textarea type="text" name="content" id="content" rows="5">{{ post_update.content }}</textarea>
            </div>
            <div>
                <label for="update_file_name">사진</label><br>
                <input type="file" name="update_file_name" id="update_file_name" />
            </div>

            {% comment %} 관리자일 경우 수정 버튼 누르면 답변 수정/삭제할 수 있음  {% endcomment %}
            {% ifequal request.session.user_class 99 %}
            <hr>
            <div>""
                <label for="answer_title">답변제목</label><br>
                <input type="text" name="answer_title" id="answer_title" value="{{ post_update.answer_title }}">
            </div>
            <div>
                <label for="answer_content">답변내용</label><br>
                <textarea type="text" name="answer_content" id="answer_content" cols="30" rows="10">{{ post_update.answer_content }}</textarea>
            </div>
            {% endifequal%}
            <input type="submit" value="수정하기" />
        </form>
    </div>
</div>

{% endblock content %}

WEB2/board/templates/board/board_write.html
{% extends "base.html" %}
{% load static %} 

{% block content %}
{% block styles %}
    <link rel="stylesheet" href="{% static 'assets/css/board_css.css' %}?after" type="text/css"/> 
{% endblock %}
<div style='height:4rem;'>
    <br>
</div>
<div id="main">
    <div class="board">
        <h2>문의게시판 <span> | 영업일 기준 1일 이내 답변됩니다!</span></h2>
            <form method="POST" action="{% url 'board:write' %}" class="post-write"  enctype="multipart/form-data">
                {% csrf_token %}
                <div>
                    <label for="title">제목</label><br>
                    <input type="text" name="title" id="title">
                </div>
                <div>
                    <label for="content">내용</label><br>
                    <textarea name="content" id="content" cols="30" rows="10"></textarea>
                </div>
                {% comment %} <div>
                    <label for="input-file" class="input-file-button">
                        파일 선택
                    </label>
                    <input type="file" name="file_name" id="input-file" style="display:none">
                    <span id="filepath" style="margin-top:0.2rem">선택된 파일 없음</span>
                </div> {% endcomment %}
                <div>
                    <input type="file" name="file_name" id="input-file">
                </div> 
                <input type="submit" value="저장하기" />
            </form>
    </div>
</div>
{% endblock content %}
{% comment %} {% block scripts %}
    <script src="{% static 'assets/js/main2.js' %}"></script>
{% endblock %} {% endcomment %}