WEB2/accountapp/urls.py
from django.urls import path
from . import views

app_name = 'accountapp'

urlpatterns = [
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('mypage/', views.mypage, name="mypage"),
    path('user_update/', views.user_update, name="user_update"),
    path('user_delete/', views.user_delete, name="user_delete"),
    path('user_qna/', views.user_qna, name="user_qna"),
    path('user_log/', views.user_log, name="user_log"),
    path('pay/', views.pay, name="pay"),
    path('agreement/', views.agreement, name="agreement"),
]

WEB2/board/urls.py
from django.urls import path
from . import views


app_name = 'board'

urlpatterns = [
    path('', views.board_list, name="board_list"),
    path('write/', views.board_write, name="write"),
    path('detail/<int:id>/', views.board_detail, name="detail"),
    path('<int:del_id>/', views.board_delete, name="delete"),
    path('update/<int:up_id>/', views.board_update, name="update"),
    path('<int:post_id>', views.file_download, name="download"),
]

WEB2/config/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/', include('homeapp.urls')),
    path('/', include('homeapp.urls')),
    path('app/analysis/', include('analysisapp.urls', namespace='analysis')),
    path('app/account/', include('accountapp.urls', namespace='account')),
    path('app/board/', include('board.urls', namespace='board')),
]

urlpatterns += \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

WEB2/homeapp/urls.py
from django.urls import path
from . import views

app_name = 'homeapp'

urlpatterns = [
    path('home/', views.home, name="home"),
    path('', views.home, name="home"),
]

WEB2/accountapp/models.py
from django.db import models
from django.db.models.fields import CharField, IntegerField, DateTimeField

label_name = 'accountapp'


class Member(models.Model):
    user_id = CharField(max_length=30, primary_key=True)
    user_pw = CharField(max_length=30)
    user_email = CharField(max_length=30)
    user_nickname = CharField(max_length=30)
    user_class = IntegerField()
    user_status = IntegerField()
    create_time = DateTimeField(auto_now_add=True)
    update_time = DateTimeField(auto_now=True)
    user_sex = IntegerField()
    user_birth = DateTimeField()

    class Meta:
        db_table = 'Member'
        app_label = label_name
        managed = False

WEB2/accountapp/forms.py
from django import forms


class searchForm(forms.Form):
    search_item = forms.CharField(max_length=150)

WEB2/accountapp/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from board.models import QABoard
from analysisapp.models import MemberLog

from accountapp.models import Member
from datetime import datetime
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.urls import reverse

import bcrypt

app_name = 'accountapp'


def board(request):
    return render(request, "accountapp/board.html")


def login(request):
    if request.method == "POST":
        user_id = request.POST.get('username')
        user_pw = request.POST.get('password')
        try:
            m = Member.objects.get(user_id=user_id)

            if not bcrypt.checkpw(user_pw.encode('utf-8'),
                                  m.user_pw.encode('utf-8')):
                m = ""

        except Exception:
            m = ""
            messages.warning(request, '잘못 입력하셨거나 존재하지 않는 사용자 정보입니다.')

        if m != "":
            request.session['user_id'] = m.user_id
            request.session['user_nickname'] = m.user_nickname
            request.session['user_class'] = m.user_class
            return redirect('/app/home')
        else:
            return render(request,
                          'accountapp/login.html',
                          {'error': 'username or password is incorrect'})
    else:
        return render(request, 'accountapp/login.html')


def logout(request):
    try:
        del request.session['user_id']
        del request.session['user_nickname']
        del request.session['user_class']
    except KeyError:
        pass
    return redirect('/app/home')


def signup(request):
    if request.method == 'POST':

        user_id = request.POST.get('username')
        user_pw = request.POST.get('password1')
        user_pw_check = request.POST.get('password2')
        user_email = request.POST.get('email')
        user_nickname = request.POST.get('nickname')
        user_class = request.POST.get('user_class')
        user_birth = request.POST.get('user_birth')
        user_sex = request.POST.get('user_sex')
        user_status = request.POST.get('user_status')

        if user_pw_check != user_pw:
            messages.info(request, '비밀번호가 일치하지 않습니다.')
            return HttpResponseRedirect(reverse('accountapp:signup'))
        try:
            Member.objects.get(user_id=user_id)

            messages.info(request, '사용중인 아이디입니다.')
            return HttpResponseRedirect(reverse('accountapp:signup'))
        except Member.DoesNotExist:

            hased_pw = bcrypt.hashpw(user_pw.encode('utf-8'), bcrypt.gensalt())
            decoded_hashed_pw = hased_pw.decode('utf-8')

            m = Member(user_id=user_id,
                       user_pw=decoded_hashed_pw,
                       user_nickname=user_nickname,
                       user_email=user_email,
                       user_class=user_class,
                       user_sex=user_sex,
                       user_status=user_status,
                       user_birth=user_birth)
            m.save()
            return HttpResponseRedirect(reverse('accountapp:login'))
    else:
        return render(request, 'accountapp/signup.html')


def mypage(request):
    return render(request, 'accountapp/mypage.html')


def user_update(request):
    if request.method == "GET":
        m = Member.objects.get(user_id=request.session['user_id'])
        return render(request, 'accountapp/user_update.html', {'m': m})

    elif request.method == "POST":
        m = Member.objects.get(user_id=request.session['user_id'])
        user_pw = request.POST.get('password1')
        user_pw_check = request.POST.get('password2')
        user_email = request.POST.get('email')
        user_nickname = request.POST.get('nickname')
        user_sex = request.POST.get('user_sex')
        user_birth = request.POST.get('user_birth')

        if user_pw != user_pw_check:
            messages.warning(request, '비밀번호가 일치하지 않습니다. 다시 시도하세요!')
        else:

            hased_pw = bcrypt.hashpw(user_pw.encode('utf-8'), bcrypt.gensalt())
            decoded_hashed_pw = hased_pw.decode('utf-8')

            m.user_pw = decoded_hashed_pw
            m.user_email = user_email
            m.user_nickname = user_nickname
            m.user_sex = user_sex
            m.user_birth = user_birth
            m.update_time = datetime.now().strftime('%Y-%m-%d')
            m.save()

            request.session['user_nickname'] = user_nickname

            return redirect('/app/account/mypage')
    return render(request, 'accountapp/user_update.html')


def user_delete(request):
    if request.method == 'POST':
        m_qaboard = QABoard.objects.filter(user_id=request.session['user_id'])
        m_qaboard.delete()

        m_member_log = MemberLog.objects.\
            filter(user_id=request.session['user_id'])
        m_member_log.delete()

        m_member = Member.objects.get(user_id=request.session['user_id'])
        m_member.delete()

        logout(request)
        return redirect('/app/home')
    return render(request, 'accountapp/user_delete.html')


def user_qna(request):
    postlist = QABoard.objects.filter(user_id=request.session['user_id'])
    return render(request, 'accountapp/user_qna.html', {'postlist': postlist})


def user_log(request):
    logs = MemberLog.objects.filter(user_id=request.session['user_id'])
    return render(request, 'accountapp/user_log.html', {'logs': logs})


def pay(request):
    return render(request, 'accountapp/pay.html')


def agreement(request):
    if request.method == "POST":
        if request.POST.get('agreement', False):
            request.session['agreement'] = True
            return redirect('/app/account/signup')
        else:
            messages.info(request, "약관에 동의해주세요.")
            return render(request, 'accountapp/agreement.html')
    else:
        request.session['agreement'] = False
        return render(request, 'accountapp/agreement.html')

WEB2/accountapp/templates/accountapp/agreement.html
{% extends "base.html" %}
{% load static %}

{% block content %}
{% block styles %}
    <link rel="stylesheet" href="{% static 'assets/css/main2.css' %}?after" type="text/css"/> 
{% endblock %}
<div style='height:4rem;'>
    <br>
</div>
<div id="main">
    <div class="s004">
        <div style="margin:10%;align-self:center;">
        <br>
        <h2 style="font-weight: bold;text-align:center;margin-bottom:2rem">개인정보 수집 및 이용 동의</h2>
            <img src="{% static 'assets/css/images/form_bar.png' %}" class="bar" style="display: block;margin: 0 auto;margin-bottom: 4rem;" />
        <div class="z-depth-1"
            style="font-size: 13px; background-color: white; border:1px solid #ddd; height:195px;overflow:auto;padding:5px;">
            <dl>
                <dt>
                    시행일자: 2022년 05월 01일
                </dt>
                <br>
                <dd>
                    본 회사(이하 "회사" 라고 함)은 통신비밀보호법, 전기통신사업법, 정보통신망 이용촉진 및 정보보호 등에 관한
                    법률 등 정보통신서비스제공자가 준수하여야 할 관련
                    법령상의 개인정보보호 규정을 준수하며, 관련 법령에 의거한 개인정보취급방침을 정하여 이용자 권익 보호에 최선을 다하고
                    있습니다.<br /><br />

                    본 개인정보취급방침은 다음과 같은 내용을 담고 있습니다.<br /><br />
                </dd>

                <dt>
                    1. 개인정보의 처리 목적
                </dt>
                <dd>
                    <ol>
                        <li>① 홈페이지 회원가입 및 관리</li>
                        <li>
                            회원 가입의사 확인, 회원제 서비스 제공에 따른 본인 식별·인증, 회원자격 유지·관리, 서비스 부정이용 방지, 각종
                            고지·통지, 고충처리, 분쟁 조정을 위한 기록
                            보존 등을 목적으로 개인정보를 처리합니다.
                        </li>
                        <li>② 민원사무 처리</li>
                        <li>민원인의 신원 확인, 민원사항 확인, 처리결과 통보 등을 목적으로 개인정보를 처리합니다.</li>
                        <li>③ 재화 또는 서비스 제공</li>
                        <li>서비스 제공, 콘텐츠 제공, 맞춤 서비스 제공, 본인인증 등을 목적으로 개인정보를 처리합니다.</li>
                        <li>④ 마케팅 및 광고에 활용</li>
                        <li>이벤트 및 광고성 정보 제공 및 참여기회 제공, 서비스의 유효성 확인, 접속빈도 파악 또는 회원의 서비스 이용에 대한 통계
                            등을 목적으로 개인정보를 처리합니다.
                        </li>
                        <li>⑤ REBORN 서비스 이용에 관한 통계 데이터 작성</li>
                        <li>보다 나은 서비스 제공을 위한 서비스 이용에 관한 통계 데이터 작성을 목적으로 개인정보를 처리합니다.</li>
                    </ol>
                </dd>
                <dt>
                    2. 처리하는 개인정보 항목
                </dt>
                <dd>
                    <ol>
                        <li>회사는 다음의 개인정보 항목을 처리하고 있습니다.<br /><br /></li>
                        <li>가. 항목 : 성명(선택사항), 닉네임, 이메일, ID, 비밀번호, 등록주소, 등록전화번호, 휴대전화번호, 서비스 이용기록
                        </li>
                        <li>나. 수집방법 : 서면양식, 홈페이지, 스마트폰 앱, 경품행사 등</li>
                        <li>다. 보유근거 : 소비자보호에 관한 법률 등 관계법령의 규정에 따라 보유</li>
                        <li>라. 보유기간: 3년</li>
                        <li>마. 관련법령:<br />
                            <ol>
                                <li>- 소비자의 불만 또는 분쟁처리에 관한 기록: 3년,</li>
                                <li>- 신용정보의 수집/처리 및 이용 등에 관한 기록: 3년</li>
                            </ol>
                        </li>
                    </ol>
                </dd>
                <dt>
                    3. 개인정보의 처리 및 보유기간
                </dt>
                <dd>
                    <ol>
                        <li>① 회사는 법령에 따른 개인정보의 보유 및 이용 기간(또는 정보주체로부터 개인정보를 수집 시에 동의 받은 개인정보 보유 및
                            이용기간)내에서 개인정보를 보유 및
                            이용합니다.</li>
                        <li>② 각각의 개인정보 보유 및 이용기간은 다음과 같습니다.
                            <ol>
                                <li>가. 홈페이지 회원가입 및 관리와 관련한 개인정보는 수집 및 이용에 관한 동의일로부터 3년까지 위 이용목적을
                                    위하여 보유 및 이용됩니다.</li>
                                <li>나. 보유근거: 전자상거래 등에서의 소비자 보호에 관한 법률</li>
                                <li>다. 관련법령: 신용정보의 수집/처리 및 이용 등에 관한 기록: 3년</li>
                            </ol>
                        </li>
                    </ol>
                </dd>
                <dt>
                    4. 쿠키 등 사용과 목적
                </dt>
                <dd>
                    <ol>
                        <li>회사는 회원과 비회원의 접속 빈도나 방문 시간 등을 분석하여 이용자의 취향과 관심분야를 파악하거나, 각종 이벤트 참여 정도
                            및 방문 회수 파악 등을 통한 타깃 마케팅
                            및 개인 맞춤 서비스 제공을 위해 쿠키를 사용합니다.</li>
                    </ol>
                </dd>
                <dt>
                    5. 개인정보 자동 수집 장치의 설치/운영 및 거부에 관한 사항
                </dt>
                <dd>
                    <ol>
                        <li>① 앱 로그 분석의 목적</li>
                        <li>이용자들이 사용한 서비스에 대한 방문 및 이용형태, 이용자 규모 등을 파악하여 이용자에게 최적화된 정보 제공을 위하여
                            사용합니다.</li>
                        <li>② 쿠키 및 개인정보 자동수집 장치 설치를 거부하였을 경우 서비스 제공에 어려움이 있을 수 있습니다.</li>
                    </ol>
                </dd>
                <dt>
                    6. 개인정보의 제3자 제공에 관한 사항
                </dt>
                <dd>
                    <ol>
                        <li>
                            ① 회사는 정보주체의 개인정보를 개인정보처리 목적에 명시한 범위 내에서만 처리하며 정보주체의 동의, 법률의 특별한 규정 등
                            개인정보보호법 제17조 및 제18조에
                            해당하는 경우에 개인정보를 제3자에게 제공합니다.
                        </li>
                        <li>
                            ② 회사는 보다 더 질 높은 서비스 제공 등을 위해 아래와 같이 귀하의 개인정보를 제공하고 있습니다.
                            <ol>
                                <li>가. 개인정보제공의 목적 : 마케팅, 클레임 처리</li>
                                <li>나. 개인정보제공 대상 : 회사의 파트너사</li>
                                <li>다. 개인정보제공 정보 : 성명(수집 선택 시), 닉네임, 이메일, 핸드폰 번호, 주소</li>
                                <li>라. 개인정보의 보유 및 이용 기간 : 회사의 회원 탈퇴 시까지</li>
                            </ol>
                        </li>
                    </ol>
                </dd>
                <dt>
                    7. 개인정보처리의 위탁에 관한 사항
                </dt>
                <dd>
                    <ol>
                        <li>① 회사는 위탁계약 체결 시 개인정보 보호법 제25조에 따라 위탁업무 수행목적 외 개인정보 처리금지, 기술적/관리적
                            보호조치, 재위탁 제한, 수탁자에 대한
                            관리/감독, 손해배상 등 책임에 관한 사항을 계약서 등 문서에 명시하고, 수탁자가 개인정보를 안전하게 처리하는지를 감독하고
                            있습니다.
                        </li>
                        <li>
                            ② 위탁업무의 내용이나 수탁자가 변경될 경우에는 지체 없이 본 개인정보 처리방침을 통하여 공개하도록 하겠습니다.
                        </li>
                    </ol>
                </dd>
                <dt>
                    8. 정보주체의 권리, 의무 및 그 행사방법에 관한 사항
                </dt>
                <dd>
                    정보주체인 이용자는 개인정보주체로서 다음과 같은 권리를 행사할 수 있습니다.<br /><br />
                    <ol>
                        <li>① 정보주체는 회사에 대해 언제든지 다음 각 호의 개인정보 보호 관련 권리를 행사할 수 있습니다.
                            <ol>
                                <li>가. 개인정보 열람요구</li>
                                <li>나. 오류 등이 있을 경우 정정 요구</li>
                                <li>다. 삭제요구</li>
                                <li>라. 처리정지 요구</li>
                            </ol>
                        </li>
                        <li>② 제1항에 따른 권리 행사는 회사에 대해 개인정보 보호법 시행규칙에 따라 서면, 이메일(E-Mail), 팩스(FAX)등을
                            통하여 하실 수 있으며 회사는 이에 대해
                            지체 없이 조치하겠습니다.</li>
                        <li>③ 정보주체가 개인정보의 오류 등에 대한 정정 또는 삭제를 요구한 경우에는 회사는 정정 또는 삭제를 완료할 때까지 당해
                            개인정보를 이용하거나 제공하지 않습니다.
                        </li>
                        <li>④ 제1항에 따른 권리 행사는 정보주체의 법정대리인이나 위임을 받은 자 등 대리인을 통하여 하실 수 있습니다. 이 경우
                            개인정보 보호법 시행규칙 별지 제11호 서식에
                            따른 위임장을 제출하셔야 합니다.</li>
                    </ol>
                </dd>
                <dt>
                    9. 개인정보의 파기
                </dt>
                <dd>
                    <ol>
                        <li>① 회사는 개인정보 보유기간의 경과 또는 개인정보 이용 및 처리목적이 달성된 경우에는 지체 없이 해당 개인정보를
                            파기합니다.</li>
                        <li>② 정보주체로부터 동의 받은 개인정보 보유기간이 경과하거나 처리목적이 달성되었음에도 불구하고 다른 법령에 따라 개인정보를
                            계속 보존하여야 하는 경우에는 해당
                            개인정보를 별도의 데이터베이스(DB)로 옮기거나 보관장소를 달리하여 보존합니다.</li>
                        <li>③ 개인정보 파기 시 종이에 출력된 개인정보는 분쇄기로 분쇄하거나 소각을 통하여 파기하고 전자적 파일형태로 저장된
                            개인정보는 기록을 재생할 수 없는 기술적 방법을
                            사용하여 삭제합니다.</li>
                    </ol>
                </dd>
                <dt>
                    10. 개인정보 처리방침 변경
                </dt>
                <dd>
                    <ol>
                        <li>① 이 개인정보처리방침은 시행일로부터 적용되며, 법령 및 방침에 따른 변경내용의 추가, 삭제 및 정정이 있는 경우에는
                            변경사항의 시행 7일 전부터 공지사항을 통하여
                            고지할 것입니다.</li>
                        <li>② 이전의 개인정보 취급방침 내용은 이전 개인정보 취급방침에서 확인할 수 있습니다.</li>
                    </ol>
                </dd>
            </dl>
        </div>
        <form method="POST" action="{% url 'account:agreement' %}" style="padding-top:10px;max-width:100%" class="agreement">
            {% csrf_token %}
            <input type="checkbox" name="agreement" id="agreement" />
            <label for="agreement">
                <span></span>
                개인정보 수집 및 이용에 동의합니다.
            </label>
            <input type="submit" value="제출하기" style="display:block;margin:2rem auto" />
        </form>
    </div>
    </div>
</form>
    </div>
    </div>
</div>
{% endblock content %}

WEB2/accountapp/templates/accountapp/login.html
{% extends "base.html" %}
{% load static %} 

{% block content %}
{% block styles %}
    <link rel="stylesheet" href="{% static 'assets/css/main2.css' %}?after" type="text/css"/> 
{% endblock %}
<div style='height:4rem;'>
  <br>
</div>
<div id="main">
  <div class="s004">
    <div class="user-loginout">
      <h2>로그인</h2>
      <img src="{% static 'assets/css/images/form_bar.png' %}" class="bar" />
      {% if request.session.user_id %}
        이미 로그인한 회원이에요!
      {% else %}
        <form method="post" action="{% url 'accountapp:login' %}" class="login">
            {% csrf_token %}
            {% include 'accountapp/form_errors.html' %}
            <div class="user-info">
              <label for="username">아이디</label>
              <input type="text" name="username" placeholder="아이디를 입력해 주세요" />
            </div>
            <div class="user-info">
              <label for="password">비밀번호</label>
              <input type="password" name="password" placeholder="비밀번호를 입력해 주세요">
            </div>

            <button type="submit" class="check-loginout" name="login_button">로그인</button>
        </form>
        <span id="user-addons">
              아직 계정이 없으신가요?
            {% comment %} <button type="button"> {% endcomment %}
                <a href="{% url 'accountapp:agreement' %}" style="text-decoration:none; color:#03B59D; font-weight:bold">회원가입</a>
            {% comment %} </button> {% endcomment %}
        </span>     
      </div>
      {% endif %}
  </div>
</div>
{%endblock content%}

WEB2/accountapp/templates/accountapp/mypage.html
{% extends "base.html" %}
{% load static %} 

{% block content %}
{% block styles %}
    <link rel="stylesheet" href="{% static 'assets/css/board_css.css' %}?after" type="text/css"/> 
{% endblock %}
<div style='height:4rem;'>
    <br>
</div>
<div id="main">
    <div class="mypage">
            <h2 style="text-align:center"> 마이페이지 </h2>
            <img src="{% static 'assets/css/images/form_bar.png' %}" class="bar" />
            <section>
                <div class="options">
                    <div class="user-modify">
                        <a href="{% url 'accountapp:user_update' %}">
                            <img src="{% static 'assets/images/메인페이지-개인정보수정.png' %}">
                        </a>
                        <a href="{% url 'accountapp:user_log' %}">
                            <img src="{% static 'assets/images/메인페이지-검색기록.png' %}">
                        </a>
                        <a href="{% url 'accountapp:user_qna' %}">
                            <img src="{% static 'assets/images/메인페이지-나의문의.png' %}">
                        </a>
                        <a href="{% url 'accountapp:user_delete' %}" id="userdelete">
                            <img src="{% static 'assets/images/메인페이지-회원탈퇴.png' %}">
                        </a>
                    </div>
                </div>
            </section>
    </div>


</div>
{%endblock content %}

WEB2/accountapp/templates/accountapp/signup.html
{% extends "base.html" %}
{% load static %}

{% block content %}
{% block styles %}
    <link rel="stylesheet" href="{% static 'assets/css/main2.css' %}?after" type="text/css"/> 
{% endblock %}
<div style='height:4rem;'>
    <br>
</div>
<div id="main">
    <div class="s004">
        <div class="user-loginout">
            <h2> 회원가입 </h2>
            <img src="{% static 'assets/css/images/form_bar.png' %}" class="bar" />
            {% if request.session.user_id %}
                이미 로그인 해 있어요!
                <button>
                    <a href="{% url 'accountapp:logout' %}" style="font-weight:bold;">로그아웃</a>
                </button>
                    {% else %}
                <form method="POST" action="{% url 'accountapp:signup' %}">
                    {% csrf_token %}
                    {% include 'accountapp/form_errors.html' %}
                    <div class="user-info">
                        <label for="username">아이디</label>
                        <input type="text" class="form-control" name="username" placeholder="아이디를 입력해주세요">
                    </div>
                    <div class="user-info">
                        <label for="password1">비밀번호</label>
                        <input type="password" class="form-control" name="password1" placeholder="비밀번호를 입력해주세요">
                    </div>
                    <div class="user-info">
                        <label for="password2">비밀번호 확인</label>
                        <input type="password" class="form-control" name="password2" placeholder="비밀번호를 다시 입력해주세요">
                    </div>
                    <div class="user-info">
                        <label for="nickname">닉네임</label>
                        <input type="text" class="form-control" name="nickname" placeholder="별명을 입력해주세요">
                    </div>
                    <div class="user-info" style="display:none">
                        <label for="validationTextarea" class="form-label" style="font-family:NanumSquareR;">구독하시겠어요?</label>
                        <select class="form-select" required aria-label="select example" style="font-family:NanumSquareR;" name="user_class">
                            <option value=0>일반회원</option>
                            <option value=1>구독</option>
                        </select>
                    </div> 
                    <div class="user-info" style="display:none">
                        <label for="validationTextarea" class="form-label" style="font-family:NanumSquareR;">유저 상태</label>
                        <select class="form-select" required aria-label="select example" style="font-family:NanumSquareR;" name="user_status">
                            <option value=0>로그아웃중</option>
                            <option value=1>로그인중</option>
                        </select>
                    </div> 
                    <div class="user-info">
                        <label for="user_birth">생년월일</label>
                        <input type="date" class="form-control" name="user_birth" min="1930-01-01" max="2022-12-31" style="width:200%;background-color: rgba(222, 222, 222, 0.25);height:3em;color:gray">
                    </div> 
                    <br/>
                    <div class="user-info">
                        <label for="validationTextarea" class="form-label" style="font-family:NanumSquareR">성별</label>
                        <select class="form-select" required aria-label="select example" style="color:gray" name="user_sex">
                            <option value=0>여</option>
                            <option value=1>남</option>
                        </select>
                    </div> 
                    <br/>
                    <div class="user-info">
                        <label for="email">이메일</label>
                        <input type="text" class="form-control" name="email" placeholder="이메일을 입력해주세요">
                    </div>
                    <button type="submit" id="check-loginout">회원가입</button>
                </form>
                <span id="user-addons2">
                    이미 계정이 있으신가요?
                    {% comment %} <button type="button"> {% endcomment %}
                        <a href="{% url 'accountapp:login' %}" style="text-decoration:none; color:#03B59D; font-weight:bold">로그인 | </a>
                        
                        <a href="{% url 'homeapp:home' %}" style="text-decoration:none; color:#03B59D; font-weight:bold">홈으로 이동</a>
                    {% comment %} </button> {% endcomment %}
                </span>
        </div> 
        {% endif %}
    </div>
</div>
{%endblock content%}

WEB2/accountapp/templates/accountapp/user_qna.html
{% extends "base.html" %}
{% load static %} 

{% block content %}
{% block styles %}
    <link rel="stylesheet" href="{% static 'assets/css/board_css.css' %}?after" type="text/css"/> 
{% endblock %}
<div style='height:4rem;'>
    <br>
</div>
<div id="main">
    <div class="board">
        <h2 class="title"> 마이페이지 > <strong style="color: #DEA742">나의 문의</strong>
            <a href="{% url 'board:write' %}" id="write-button" style="margin:2.5rem 2rem 1rem 0;font-size:1rem;">
                문의글쓰기 >
            </a>         
        </h2>

        <section class="qna_list">
            <table class="table" style="table-layout:auto">
                <thead class="thead-light" style="display:none">
                    <tr class="text-center">
                        <th scope="col">#</th>
                        <th scope="col">답변유무</th>
                        <th scope="col">제목</th>
                        <th scope="col">작성자</th>
                    </tr>
                </thead>

                <div class="container">
                    <tbody>
                        {% for list in postlist reversed %}
                        <tr class="text-center">
                            <th scope="row" width=5% class="board_td">
                                <span>{{ list.id }}</span>
                            </th>
                            <td width=10%>
                                {% if list.answer_title %}
                                    <img src="{% static 'assets/images/게시판_답변완료.png' %}" />
                                {% else %}
                                    <img  src="{% static 'assets/images/게시판_미답변.png' %}" />
                                {% endif %}
                            </td>
                            <td width=75% class="board_td">
                                <a href="{% url 'board:detail' id=list.id %}">
                                <span>{{ list.title }}</span>
                                </a>
                            </td>
                            <td width=10% class="board_td">
                                <span>{{ list.user_id }}</span>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
            </table>
            </div>
        </section>
    </div>


</div>
{% endblock %}