WEB2/accountapp/urls.py
from django.urls import path
from . import views

app_name = 'accountapp'

urlpatterns = [
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('mypage/', views.mypage, name="mypage"),
    path('user_update/', views.user_update, name="user_update"),
    path('user_delete/', views.user_delete, name="user_delete"),
    path('user_qna/', views.user_qna, name="user_qna"),
    path('user_log/', views.user_log, name="user_log"),
    path('pay/', views.pay, name="pay"),
    path('agreement/', views.agreement, name="agreement"),
]

WEB2/analysisapp/urls.py
from django.urls import path
from . import views

app_name = 'analysisapp'

urlpatterns = [
    path('result/', views.result, name='result'),
    path('detail/<int:sentiment_id>', views.detail, name='detail'),
]

WEB2/board/urls.py
from django.urls import path
from . import views


app_name = 'board'

urlpatterns = [
    path('', views.board_list, name="board_list"),
    path('write/', views.board_write, name="write"),
    path('detail/<int:id>/', views.board_detail, name="detail"),
    path('<int:del_id>/', views.board_delete, name="delete"),
    path('update/<int:up_id>/', views.board_update, name="update"),
    path('<int:post_id>', views.file_download, name="download"),
]

WEB2/config/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/', include('homeapp.urls')),
    path('/', include('homeapp.urls')),
    path('app/analysis/', include('analysisapp.urls', namespace='analysis')),
    path('app/account/', include('accountapp.urls', namespace='account')),
    path('app/board/', include('board.urls', namespace='board')),
]

urlpatterns += \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

WEB2/homeapp/urls.py
from django.urls import path
from . import views

app_name = 'homeapp'

urlpatterns = [
    path('home/', views.home, name="home"),
    path('', views.home, name="home"),
]

WEB2/templates/base.html
<!DOCTYPE html>
 <html lang="ko">
    {% include 'base_head.html' %}
    <body class="is-preload">
        <!-- base_headerBar -->
        {% include 'base_headerBar.html' %}
        <!-- Wrapper -->
	    <div id="wrapper">
            <!-- Main -> 무엇이든 재사용 가능할 틀로 수정-->
            {% block content %} 
            {% endblock %}
            <!-- Footer -->
            {% include 'base_footer.html' %}
        </div>
        {% include 'base_Scripts.html' %}
    </body>
</html>

WEB2/templates/base_Scripts.html
{% load static %}
<!-- Scripts -->
<script src="{% static 'assets/js/jquery.min.js'%}"></script>
<script src="{% static 'assets/js/jquery.scrollex.min.js'%}"></script>
<script src="{% static 'assets/js/jquery.scrolly.min.js'%}"></script>
<script src="{% static 'assets/js/browser.min.js'%}"></script>
<script src="{% static 'assets/js/breakpoints.min.js'%}"></script>
<script src="{% static 'assets/js/util.js'%}"></script>
<script src="{% static 'assets/js/main.js'%}"></script>
{% comment %} <script src="{% static 'assets/js/title.js'%}"></script> {% endcomment %}

WEB2/templates/base_footer.html
{%load static%}
<footer id="footer">
    {% comment %} <section>
        <h2>Aliquam sed mauris</h2>
        <p>Sed lorem ipsum dolor sit amet et nullam consequat feugiat consequat magna adipiscing tempus etiam dolore veroeros. eget dapibus mauris. Cras aliquet, nisl ut viverra sollicitudin, ligula erat egestas velit, vitae tincidunt odio.</p>
        <ul class="actions">
            <li><a href="generic.html" class="button">Learn More</a></li>
        </ul>
    </section>
    <section>
        <h2>Etiam feugiat</h2>
        <dl class="alt">
            <dt>Address</dt>
            <dd>1234 Somewhere Road &bull; Nashville, TN 00000 &bull; USA</dd>
            <dt>Phone</dt>
            <dd>(000) 000-0000 x 0000</dd>
            <dt>Email</dt>
            <dd><a href="#">information@untitled.tld</a></dd>
        </dl>
        <ul class="icons">
            <li><a href="#" class="icon brands fa-twitter alt"><span class="label">Twitter</span></a></li>
            <li><a href="#" class="icon brands fa-facebook-f alt"><span class="label">Facebook</span></a></li>
            <li><a href="#" class="icon brands fa-instagram alt"><span class="label">Instagram</span></a></li>
            <li><a href="#" class="icon brands fa-github alt"><span class="label">GitHub</span></a></li>
            <li><a href="#" class="icon brands fa-dribbble alt"><span class="label">Dribbble</span></a></li>
        </ul>
    </section> {% endcomment %}
    <p class="copyright" style="text-align: center;"><img class="footimg" src="{% static 'assets/images/그림2.png'%}" alt="image" /></p>
</footer>

WEB2/templates/base_head.html
{%load static%}

<head>
    <title>REVIEW MASTER</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
    <link rel="stylesheet" href="{% static 'assets/css/main3.css'%}"/>
    <noscript><link rel="stylesheet" href="{% static 'assets/css/noscript.css'%}" /></noscript>
    <link rel="stylesheet" href="{% static 'assets/css/choose.css'%}"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tiny-slider/2.9.2/tiny-slider.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css">
    <link href="https://hangeul.pstatic.net/hangeul_static/css/nanum-square.css" rel="stylesheet">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'assets/images/mark.png'%}">
    {% block styles %}
    {% endblock %}
</head>

WEB2/templates/base_headerBar.html
{% load static %}

<div class="hbody">
    <article class="head_nav">
        <div class="head_title">
            <a href="{% url 'homeapp:home' %}">
                <img src="{% static 'assets/images/final_logo.png' %}"  class="logo" />
            </a>
        </div>
        {% if request.session.user_id %}
        <div class="head_content">
            <ul id="head_menu">
                <li class='head_li'><a href="{% url 'homeapp:home' %}">Home</a></li>
                <li class='head_li bar'>|</li>
                <li class='head_li'><a href="{% url 'accountapp:pay' %}">요금제</a></li>
                <li class='head_li bar'>|</li>
                <li class='head_li'><a href="{% url 'board:board_list' %}">질문게시판</a></li>
                <li class='head_li bar'>|</li>
                <li class='head_li'><a href="{% url 'accountapp:mypage' %}">마이페이지</a></li>
            </ul>
        </div>
        <div class="head_user">
            <ul id="head_menu">
                <li class='head_li'><a href="{% url 'accountapp:logout' %}">logout</a></li>
                <li class='head_li bar'>|</>
                <li class='head_li'><a href="{% url 'accountapp:mypage' %}" style="font-weight:bold">{{ request.session.user_nickname }}</a></li>
            </ul>
        </div>

        {% else %}
        <div class="head_content">
            <ul id="head_menu">
                <li class='head_li'><a href="{% url 'homeapp:home' %}">Home</a></li>
                <div class='head_li bar'>|</div>
                <li class='head_li'><a href="{% url 'accountapp:pay' %}">요금제</a></li>
                <div class='head_li bar'>|</div>
                <li class='head_li'><a href="{% url 'board:board_list' %}">질문게시판</a></li>
            </ul>
        </div>
        <div class="head_user">
            <ul id="head_menu">
                <li class='head_li'><a href="{% url 'accountapp:login' %}">login</a></li>
                <div class='head_li bar'>|</div>
                <li class='head_li' id="nickname"><a href="{% url 'accountapp:agreement' %}">sign up</a></li>
            </ul>
        </div>
        {% endif %}
        <div class="hamburger">
            <img src="{% static '/assets/images/hamburger.svg' %}" />
        </div>
    </article>
</div>

{% block scripts %}
    <script src="{% static 'assets/js/main2.js' %}"></script>
{% endblock %}

WEB2/templates/base_navigator.html
{%load static%}

<nav id="nav">
    <ul>
        <li><a href="#intro" class="active">오늘의 추천검색어</a></li>
        <li><a href="#allhot">전체 핫 키워드</a></li>
        <li><a href="#2030year">2030 인기검색어</a></li>
        <li><a href="#4050year">4050 인기검색어</a></li>
    </ul>
</nav>

WEB2/templates/base_navigator_analysis.html
{%load static%}

<nav id="nav">
    <ul>
        <li><a href="#description2" class="active">리뷰요약</a></li>
        <li><a href="#review">순수 리뷰 목록</a></li>
        <li><a href="#associate">연관어 분석</a></li>
        <!-- <li><a href="#emotion">감성어 분석</a></li> -->
        <li><a href="#purchase">구매 링크</a></li>
    </ul>
</nav>

WEB2/templates/base_search_form.html
{%load static%}
<header id="header" class="alt">				  
    <!-- <span class="logo"><img src="images/logo.svg" alt="" /></span> -->
    <h2 class="result">관심있는 전자제품 우리가 AI로 분석할게 넌 결정만해</h2>
</header>
<form class='search_form' method = "get" action = "{% url 'analysisapp:result' %}">
    <div class="search_div">
        <input class="input1" type="text" placeholder="제조사" name = "company" />
        <input class="input2" type="text" placeholder="관심상품명을 입력해주세요" name = "article_name"/>
        <button class="input3" type="submit">
            <svg xmlns="http://www.w3.org/2000/svg" id="svgsearch" width="24" height="24" viewBox="0 0 24 24">
                <path d="M15.5 14h-.79l-.28-.27C15.41 12.59 16 11.11 16 9.5 16 5.91 13.09 3 9.5 3S3 5.91 3 9.5 5.91 16 9.5 16c1.61 0 3.09-.59 4.23-1.57l.27.28v.79l5 4.99L20.49 19l-4.99-5zm-6 0C7.01 14 5 11.99 5 9.5S7.01 5 9.5 5 14 7.01 14 9.5 11.99 14 9.5 14z"></path>
            </svg>
        </button>
    </div>
</form>

WEB2/templates/double_base_bone.html
{% extends "base.html" %}
{% load static %} 

{% block content %}
    {% include 'base_search_form.html' %}
    <!-- Nav navigator-->
    {% if select_num == 1 %}
        {% include 'base_navigator_analysis.html' %}
    {% else %}
        {% include 'base_navigator.html' %}
    {% endif %}
        <!-- Main -->
    <div id="main">
        <!-- Introduction homeapp contents.html -->
        {% block contents %} 
        {% endblock %}
    </div>
{%endblock content %}